/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'music' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'marketing' : null } |
  { 'design' : null } |
  { 'business' : null } |
  { 'writing' : null } |
  { 'programming' : null };
export interface Service {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'sellerName' : string,
  'category' : Category,
  'sellerId' : Principal,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createService' : ActorMethod<
    [string, string, number, Category, string],
    bigint
  >,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'editService' : ActorMethod<
    [bigint, string, string, number, Category],
    undefined
  >,
  'getAllActiveServices' : ActorMethod<
    [[] | [Category], [] | [boolean]],
    Array<Service>
  >,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getServiceByCategory' : ActorMethod<[Category], Array<Service>>,
  'getServiceById' : ActorMethod<[bigint], [] | [Service]>,
  'getServiceCount' : ActorMethod<[], bigint>,
  'getServiceStats' : ActorMethod<
    [],
    { 'total' : bigint, 'active' : bigint, 'inactive' : bigint }
  >,
  'getServicesBySeller' : ActorMethod<[Principal], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServices' : ActorMethod<[string], Array<Service>>,
  'toggleServiceActive' : ActorMethod<[bigint], { 'active' : boolean }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];