/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'music' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'marketing' : IDL.Null,
  'design' : IDL.Null,
  'business' : IDL.Null,
  'writing' : IDL.Null,
  'programming' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'category' : Category,
  'sellerId' : IDL.Principal,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'editService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, Category],
      [],
      [],
    ),
  'getAllActiveServices' : IDL.Func(
      [IDL.Opt(Category), IDL.Opt(IDL.Bool)],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getServiceByCategory' : IDL.Func([Category], [IDL.Vec(Service)], ['query']),
  'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServiceCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getServiceStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'active' : IDL.Nat,
          'inactive' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getServicesBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'toggleServiceActive' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'active' : IDL.Bool })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'music' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'marketing' : IDL.Null,
    'design' : IDL.Null,
    'business' : IDL.Null,
    'writing' : IDL.Null,
    'programming' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'category' : Category,
    'sellerId' : IDL.Principal,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'editService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, Category],
        [],
        [],
      ),
    'getAllActiveServices' : IDL.Func(
        [IDL.Opt(Category), IDL.Opt(IDL.Bool)],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getServiceByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getServiceById' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServiceCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getServiceStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'active' : IDL.Nat,
            'inactive' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getServicesBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
    'toggleServiceActive' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'active' : IDL.Bool })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };